name: Artifact Publish Token
description: Retrieves publish token for packages.atlassian.com
inputs:
  output-mode:
    description: How to export the token. Any comma separated combination of {environment, output, maven, gradle}. Defaults to output
    default: output
outputs:
  artifact-username:
    description: Token username
  artifact-token:
    description: Token value
runs:
  using: 'node16'
  main: 'dist/index.js'
