image: "node:16-slim"
definitions:
  steps:
    - step: &test
        name: Test
        caches:
          - node
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - npm install
          - npm run test
    - step: &build
        name: Build
        caches:
          - node
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - npm install
          - npm run build

    - step: &release
        name: Tag Release
        caches:
          - node
        deployment: production
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - apt-get update && apt-get install -y git
          # backup BBP's own ssh key that will be used later
          - mv ${SSH_KEY_PATH}/id_rsa ${SSH_KEY_PATH}/id_rsa-bbp
          - (echo ${SECART_BOT_SSH_KEY} | base64 --decode > ${SSH_KEY_PATH}/id_rsa)
          - npm install
          - npm run release
          # restore the BBP's ssh to push to Github
          - mv ${SSH_KEY_PATH}/id_rsa-bbp ${SSH_KEY_PATH}/id_rsa
          - git push git@github.com:atlassian-labs/artifact-publish-token.git HEAD:main --follow-tags
pipelines:
  default:
    - parallel:
        - step: *test
        - step: *build
  branches:
    main:
      - parallel:
          - step: *test
          - step: *build
      - step: *release
