image: "node:16-slim"
definitions:
  steps:
    - step: &test
        name: Test
        caches:
          - node
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - npm install
          - npm run test
    - step: &build
        name: Build
        caches:
          - node
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - npm install
          - npm run build

    - step: &release
        name: Tag Release
        caches:
          - node
        script:
          - pipe: atlassian/artifactory-sidekick:v1
          - source .artifactory/activate.sh
          - apt-get update && apt-get install -y git
          - npm install
          - npm run release
          - git push git@github.com:atlassian-labs/artifact-publish-token.git HEAD:main --follow-tags
pipelines:
  default:
    - parallel:
        - step: *test
        - step: *build
  branches:
    main:
      - parallel:
          - step: *test
          - step: *build
      - step: *release
