# This is a basic workflow to help you get started with Actions

name: Test Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get publish token
        id: publish-token
        uses: atlassian-labs/oidc-test@v1.0.0
        with:
          output-mode: maven
      - name: Check maven settings
        run: ls -ltr ~/

      # - name: Install OIDC Client
      #   run: npm install @actions/core@1.6.0 @actions/http-client
      # - name: Get Id Token
      #   uses: actions/github-script@v4
      #   id: getIdToken
      #   with:
      #     script: |
      #       const someCore = require('@actions/core')
      #       let id_token = await someCore.getIDToken()
      #       core.setOutput('id_token', id_token)
      # - name: Echo Id Token
      #   run: |
      #     echo "Id Token ${{ steps.getIdToken.outputs.id_token }}"
      #     curl -XPOST "https://artifactory-oidc.services.atlassian.com/oidc/token?provider=github" -H"Authorization: Bearer ${{ steps.getIdToken.outputs.id_token }}"




